coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
      main:
        target: 75%
        threshold: 0%
        base: auto
        branches:
          - main
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto
