name: Continous Deployment

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      -
        name: Create A Release
        id: release-please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          command: manifest
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      -
        name: Dispatch Edge Build
        if: always()
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          repository: opencadc/canfar
          event-type: edge-build
          token: ${{ secrets.GITHUB_TOKEN }}
          client-payload: |-
            {
              "releases_created": "${{ steps.release-please.outputs.releases_created }}",
              "tag_name": "${{ steps.release-please.outputs.tag_name }}",
              "sha": "${{ steps.release-please.outputs.sha }}"
            }
      -
        name: Dispatch Release Build
        if: ${{ steps.release-please.outputs.release_created }}
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          repository: opencadc/canfar
          event-type: release-build
          token: ${{ secrets.GITHUB_TOKEN }}
          client-payload: |-
            {
              "releases_created": "${{ steps.release-please.outputs.releases_created }}",
              "tag_name": "${{ steps.release-please.outputs.tag_name }}",
              "sha": "${{ steps.release-please.outputs.sha }}"
            }
      -
        #! TODO: Enable the PYPI build, once confguration is confirmed.
        name: Dispatch PYPI Release
        if: ${{ steps.release-please.outputs.release_created }}
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          repository: opencadc/canfar
          event-type: pypi-release
          token: ${{ secrets.GITHUB_TOKEN }}
          client-payload: |-
            {
              "releases_created": "${{ steps.release-please.outputs.releases_created }}",
              "tag_name": "${{ steps.release-please.outputs.tag_name }}",
              "sha": "${{ steps.release-please.outputs.sha }}"
            }
      -
        name: Dispatch Docs Publish
        if: always()
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          repository: opencadc/canfar
          event-type: docs-publish
          token: ${{ secrets.GITHUB_TOKEN }}
          client-payload: |-
            {
              "releases_created": "${{ steps.release-please.outputs.releases_created }}",
              "tag_name": "${{ steps.release-please.outputs.tag_name }}",
              "sha": "${{ steps.release-please.outputs.sha }}"
            }
