name: Edge Container Build

on:
  repository_dispatch:
    types: [edge-build]

permissions:
  contents: read

jobs:
  edge-build:
    uses: ./.github/workflows/reusable-container.yml
    permissions:
      packages: write
      attestations: write
      id-token: write
    with:
      client-payload: ${{ toJson(github.event.client_payload) }}
      image-description: Python Client for CANFAR Science Platform
      image-tags: ghcr.io/opencadc/canfar:edge
      image-version: edge
