name: Publish CANFAR to Container Registries

on:
  repository_dispatch:
    types: [release-build]

permissions:
  contents: read

jobs:
  release-build:
    uses: ./.github/workflows/reusable-container.yml
    permissions:
      packages: write # Upload package to ghcr.io
      attestations: write # Attest the build provenance
      id-token: write # Genereate OIDC token for attestations
    with:
      client-payload: ${{ toJson(github.event.client_payload) }}
      checkout-ref: ${{ github.event.client_payload.tag_name }}
      image-description: Python Client for CANFAR Science Portal
      image-tags: |
        ghcr.io/opencadc/canfar:${{ github.event.client_payload.tag_name }}
        ghcr.io/opencadc/canfar:latest
      image-version: ${{ github.event.client_payload.tag_name }}
